groups:
  - name: mobile_devs
    reviewers: 1
    usernames: # github usernames of the reviewers
      - emanuelebeffa
      - Danilospano00
      - MattMe99
      - GangemiLorenzo
      - MatteoBoe97
      - pdario98
